name: 'metadata_macros'
version: '1.0.0'
config-version: 2

profile: 'default'

macro-paths: ["macros"]
model-paths: ["models"]
target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"

